services:
  mysql-db:
    image: mysql:8.0
    container_name: todolist-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todolist_db
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todolist-network

  todolist-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/todolist_db?allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: todouser
      SPRING_DATASOURCE_PASSWORD: todopassword
    depends_on:
      - mysql-db
    networks:
      - todolist-network

volumes:
  mysql_data:

networks:
  todolist-network:
    driver: bridge